[package]
name = "stream-jenkins-logs"
description = "Stream jenkins logs for a given build"
version = "0.1.0"
authors = ["Stefan Ruzitschka <icepuma@godda.mn>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
clap = "2.33.0"
url = "1.7.2"
